"""
Butterfly species detail database.

Each key matches a class name from prediction.py's `classes` list.
Fields: scientific (Latin name), desc (short blurb), habitat, common (region).
"""

BUTTERFLY_DETAILS = {
    'ADONIS': {
        'scientific': 'Polyommatus bellargus',
        'desc': 'The Adonis Blue is a striking lycaenid butterfly. Males display vivid sky-blue upper wings edged with a thin black line and white fringe.',
        'habitat': 'Chalk Grassland',
        'common': 'Europe',
    },
    'AFRICAN GIANT SWALLOWTAIL': {
        'scientific': 'Papilio antimachus',
        'desc': 'The largest butterfly in Africa with a wingspan up to 25 cm. Its bright orange-brown wings with black markings make it unmistakable.',
        'habitat': 'Tropical Rainforest',
        'common': 'Central & West Africa',
    },
    'AMERICAN SNOOT': {
        'scientific': 'Libytheana carinenta',
        'desc': 'Named for its elongated mouthparts that resemble a snout. The angular wing shape and brown coloration provide excellent camouflage among dead leaves.',
        'habitat': 'Woodland Edges',
        'common': 'North & Central America',
    },
    'AN 88': {
        'scientific': 'Diaethria anna',
        'desc': 'Famous for the striking black-and-white "88" or "89" pattern on its hindwing underside. The upper wings flash a brilliant blue-black.',
        'habitat': 'Tropical Forest',
        'common': 'Central & South America',
    },
    'APPOLLO': {
        'scientific': 'Parnassius apollo',
        'desc': 'A large, semi-translucent white butterfly adorned with bold red and black eye-spots. It is a protected species across much of Europe.',
        'habitat': 'Alpine Meadows',
        'common': 'Europe & Central Asia',
    },
    'ATALA': {
        'scientific': 'Eumaeus atala',
        'desc': 'A small, brilliantly colored butterfly once thought to be extinct in Florida. Its velvety black wings are dotted with iridescent blue-green spots.',
        'habitat': 'Coastal Scrubland',
        'common': 'Southeast Florida & Caribbean',
    },
    'BANDED ORANGE HELICONIAN': {
        'scientific': 'Dryadula phaetusa',
        'desc': 'A large, bright orange butterfly with bold black tiger-like stripes. It has an elongated wing shape typical of heliconians.',
        'habitat': 'Open Fields & Riverbanks',
        'common': 'Central & South America',
    },
    'BANDED PEACOCK': {
        'scientific': 'Papilio crino',
        'desc': 'A swallowtail with a broad emerald-green band across dark velvety wings. The hindwings bear elegant tail-like extensions.',
        'habitat': 'Deciduous Forest',
        'common': 'South & Southeast Asia',
    },
    'BECKERS WHITE': {
        'scientific': 'Pontia beckerii',
        'desc': 'A medium-sized white butterfly with greenish marbling on the hindwing underside. It thrives in arid, open habitats of the western US.',
        'habitat': 'Desert & Sagebrush',
        'common': 'Western North America',
    },
    'BLACK HAIRSTREAK': {
        'scientific': 'Satyrium pruni',
        'desc': 'A small, elusive butterfly with rich brown wings accented by a row of orange lunules and fine white hairstreak lines on the underside.',
        'habitat': 'Blackthorn Thickets',
        'common': 'Europe',
    },
    'BLUE MORPHO': {
        'scientific': 'Morpho menelaus',
        'desc': 'Iconic for its dazzling iridescent blue upper wings, caused by microscopic scales that reflect light. The brown underside provides camouflage.',
        'habitat': 'Tropical Rainforest',
        'common': 'Central & South America',
    },
    'BLUE SPOTTED CROW': {
        'scientific': 'Euploea midamus',
        'desc': 'A large, dark brown butterfly covered with pale blue spots and streaks. Like other crows, it is distasteful to predators.',
        'habitat': 'Mangroves & Coastal Forest',
        'common': 'South & Southeast Asia',
    },
    'BROWN SIPROETA': {
        'scientific': 'Siproeta epaphus',
        'desc': 'A neotropical brush-foot with rich chocolate-brown wings crossed by creamy-white and orange bands. Often seen basking on forest trails.',
        'habitat': 'Cloud Forest',
        'common': 'Central & South America',
    },
    'CABBAGE WHITE': {
        'scientific': 'Pieris rapae',
        'desc': 'One of the most common butterflies worldwide. Its plain white wings with small black dots belie its remarkable adaptability and global spread.',
        'habitat': 'Gardens & Farmland',
        'common': 'Worldwide',
    },
    'CAIRNS BIRDWING': {
        'scientific': 'Ornithoptera euphorion',
        'desc': 'Australia\'s largest endemic butterfly. Males display vivid green and black wings, while females are larger with brown and white markings.',
        'habitat': 'Tropical Rainforest',
        'common': 'Northeast Australia',
    },
    'CHECQUERED SKIPPER': {
        'scientific': 'Carterocephalus palaemon',
        'desc': 'A small skipper with a distinctive checkerboard pattern of dark brown and golden-yellow spots. It has a rapid, darting flight.',
        'habitat': 'Woodland Clearings',
        'common': 'Europe & North America',
    },
    'CHESTNUT': {
        'scientific': 'Junonia iphita',
        'desc': 'A warm brown butterfly with subtle darker eyespots and wavy wing margins. It prefers shaded habitats and is often found resting on the ground.',
        'habitat': 'Shaded Forest',
        'common': 'South & Southeast Asia',
    },
    'CLEOPATRA': {
        'scientific': 'Gonepteryx cleopatra',
        'desc': 'The male has bright yellow forewings with a vivid orange flush, while the female is pale greenish-white. A close relative of the Brimstone.',
        'habitat': 'Mediterranean Scrubland',
        'common': 'Southern Europe & North Africa',
    },
    'CLODIUS PARNASSIAN': {
        'scientific': 'Parnassius clodius',
        'desc': 'A semi-translucent white butterfly with smoky dark wing margins and small red spots. Found in mountainous regions of western North America.',
        'habitat': 'Mountain Meadows',
        'common': 'Western North America',
    },
    'CLOUDED SULPHUR': {
        'scientific': 'Colias philodice',
        'desc': 'A common yellow butterfly with sharply defined black wing borders. The underside features a silver-centered spot ringed in pink.',
        'habitat': 'Open Fields & Roadsides',
        'common': 'North America',
    },
    'COMMON BANDED AWL': {
        'scientific': 'Hasora chromus',
        'desc': 'A robust, fast-flying skipper with dark brown wings and a distinctive white band across the hindwing underside.',
        'habitat': 'Forest & Garden Edges',
        'common': 'South & Southeast Asia',
    },
    'COMMON WOOD-NYMPH': {
        'scientific': 'Cercyonis pegala',
        'desc': 'A medium brown butterfly with prominent yellow-ringed eyespots on the forewings. It flies with a slow, bobbing motion close to the ground.',
        'habitat': 'Grassland & Open Woodland',
        'common': 'North America',
    },
    'COPPER TAIL': {
        'scientific': 'Philaethria dido',
        'desc': 'A large heliconian with translucent green wings and dark veins, sometimes called the Scarce Bamboo Page. Graceful in flight.',
        'habitat': 'Tropical Forest Canopy',
        'common': 'Central & South America',
    },
    'CRECENT': {
        'scientific': 'Phyciodes tharos',
        'desc': 'The Pearl Crescent is a small orange-and-black butterfly. Its crescent-shaped pale markings on the hindwing underside give it its name.',
        'habitat': 'Open Fields & Meadows',
        'common': 'North America',
    },
    'CRIMSON PATCH': {
        'scientific': 'Chlosyne janais',
        'desc': 'A striking brush-foot featuring jet-black wings with a large crimson-red patch on the hindwings. Vivid and unmistakable.',
        'habitat': 'Subtropical Woodland',
        'common': 'Southern Texas to Central America',
    },
    'DANAID EGGFLY': {
        'scientific': 'Hypolimnas misippus',
        'desc': 'The female is a remarkable mimic of the toxic Plain Tiger butterfly. Males are velvety black with iridescent white-centred blue patches.',
        'habitat': 'Open Woodland & Gardens',
        'common': 'Africa, Asia & Australia',
    },
    'EASTERN COMA': {
        'scientific': 'Polygonia comma',
        'desc': 'Named for the small silver comma-shaped mark on its hindwing underside. The ragged wing edges provide excellent leaf-like camouflage.',
        'habitat': 'Deciduous Woodland',
        'common': 'Eastern North America',
    },
    'EASTERN DAPPLE WHITE': {
        'scientific': 'Euchloe ausonia',
        'desc': 'A delicate white pierid with mossy green marbling on the hindwing underside, offering superb camouflage when resting on flower heads.',
        'habitat': 'Dry Hillsides & Meadows',
        'common': 'Southern Europe & Western Asia',
    },
    'EASTERN PINE ELFIN': {
        'scientific': 'Callophrys niphon',
        'desc': 'A small, intricately patterned brown butterfly whose hindwing underside shows bold banding that mimics pine bark.',
        'habitat': 'Pine & Mixed Forest',
        'common': 'Eastern North America',
    },
    'ELBOWED PIERROT': {
        'scientific': 'Caleta elna',
        'desc': 'A tiny lycaenid with snow-white wings marked in black spots and an angular hindwing shape that gives it its "elbowed" name.',
        'habitat': 'Tropical Forest Edge',
        'common': 'South & Southeast Asia',
    },
    'GOLD BANDED': {
        'scientific': 'Godyris zavaleta',
        'desc': 'A clearwing butterfly with transparent panels bordered by golden-orange bands. It belongs to the ithomiine tribe of brush-foots.',
        'habitat': 'Cloud Forest',
        'common': 'Central & South America',
    },
    'GREAT EGGFLY': {
        'scientific': 'Hypolimnas bolina',
        'desc': 'Males are jet-black with large white egg-shaped spots fringed in iridescent purple-blue. Females are polymorphic mimics.',
        'habitat': 'Gardens & Forest Edges',
        'common': 'Asia, Australia & Pacific',
    },
    'GREAT JAY': {
        'scientific': 'Graphium eurypylus',
        'desc': 'A swallowtail with pale blue-green translucent spots arranged in bands across black wings. It has a swift, sailing flight.',
        'habitat': 'Tropical & Subtropical Forest',
        'common': 'Southeast Asia & Australia',
    },
    'GREEN CELLED CATTLEHEART': {
        'scientific': 'Parides childrenae',
        'desc': 'A dark swallowtail with rows of green-tinted translucent cells on the hindwings and red body spots warning of its toxicity.',
        'habitat': 'Tropical Rainforest',
        'common': 'South America',
    },
    'GREY HAIRSTREAK': {
        'scientific': 'Strymon melinus',
        'desc': 'One of the most widespread hairstreaks in North America. Plain grey above, the underside shows a fine orange-dotted line and delicate tails.',
        'habitat': 'Open Areas & Gardens',
        'common': 'North & Central America',
    },
    'INDRA SWALLOW': {
        'scientific': 'Papilio indra',
        'desc': 'A compact, short-tailed swallowtail with bold black-and-yellow bands. It is closely tied to rocky canyon habitats and specific host plants.',
        'habitat': 'Rocky Canyons & Desert',
        'common': 'Western North America',
    },
    'IPHICLUS SISTER': {
        'scientific': 'Adelpha iphiclus',
        'desc': 'A brush-foot with dark brown wings crossed by a bold white-orange median band. It glides gracefully along forest paths.',
        'habitat': 'Tropical Forest',
        'common': 'Central & South America',
    },
    'JULIA': {
        'scientific': 'Dryas iulia',
        'desc': 'The Julia Heliconian has long, narrow wings of bright orange. It is an active, fast flier often seen visiting lantana flowers.',
        'habitat': 'Open Woodland & Gardens',
        'common': 'Southern US to South America',
    },
    'LARGE MARBLE': {
        'scientific': 'Euchloe ausonides',
        'desc': 'A white pierid with bold greenish-yellow marbling on the hindwing underside. It flies in spring through mountain meadows.',
        'habitat': 'Mountain Meadows',
        'common': 'Western North America',
    },
    'MALACHITE': {
        'scientific': 'Siproeta stelenes',
        'desc': 'Named for its vivid green malachite-like patterning on black wings. A large, showy butterfly often found basking with open wings.',
        'habitat': 'Subtropical Forest & Gardens',
        'common': 'Southern US to South America',
    },
    'MANGROVE SKIPPER': {
        'scientific': 'Phocides pigmalion',
        'desc': 'A large, robust skipper with dark wings streaked in iridescent blue. It is strongly associated with mangrove habitats in coastal areas.',
        'habitat': 'Mangroves & Coastal Areas',
        'common': 'Florida & Caribbean',
    },
    'MESTRA': {
        'scientific': 'Mestra amymone',
        'desc': 'The Common Mestra is a pale, delicate brush-foot with greyish-white wings and a subtle orange patch on the forewing.',
        'habitat': 'Brushy Fields & Roadsides',
        'common': 'Southern US to Central America',
    },
    'METALMARK': {
        'scientific': 'Calephelis virginiensis',
        'desc': 'A tiny butterfly with rust-orange wings accented by metallic silvery spots along the margins, giving the family its name.',
        'habitat': 'Grassy Woodland',
        'common': 'North & South America',
    },
    'MILBERTS TORTOISESHELL': {
        'scientific': 'Aglais milberti',
        'desc': 'A dark brush-foot with a broad sunburst band of orange and yellow near the wing margins. The underwings mimic dark tree bark.',
        'habitat': 'Moist Meadows & Streamsides',
        'common': 'North America',
    },
    'MONARCH': {
        'scientific': 'Danaus plexippus',
        'desc': 'Perhaps the world\'s most famous butterfly, renowned for its epic multi-generational migration spanning thousands of miles.',
        'habitat': 'Fields & Meadows',
        'common': 'North America',
    },
    'MOURNING CLOAK': {
        'scientific': 'Nymphalis antiopa',
        'desc': 'A large, long-lived butterfly with velvety maroon wings bordered by a creamy-yellow edge and a row of iridescent blue spots.',
        'habitat': 'Deciduous Woodland',
        'common': 'North America & Eurasia',
    },
    'ORANGE OAKLEAF': {
        'scientific': 'Kallima inachus',
        'desc': 'A master of disguise — the underside is a near-perfect dead leaf mimic, while the upper wings flash brilliant orange and blue.',
        'habitat': 'Tropical Forest',
        'common': 'South & Southeast Asia',
    },
    'ORANGE TIP': {
        'scientific': 'Anthocharis cardamines',
        'desc': 'Males have white wings with bold orange tips on the forewings. The mottled green underside provides camouflage among spring wildflowers.',
        'habitat': 'Meadows & Hedgerows',
        'common': 'Europe & Western Asia',
    },
    'ORCHARD SWALLOW': {
        'scientific': 'Papilio demodocus',
        'desc': 'A large citrus swallowtail with yellow-spotted black wings. Commonly seen in gardens and orchards where citrus trees are grown.',
        'habitat': 'Orchards & Gardens',
        'common': 'Sub-Saharan Africa',
    },
    'PAINTED LADY': {
        'scientific': 'Vanessa cardui',
        'desc': 'The most cosmopolitan butterfly on Earth, found on every continent except Antarctica. Orange wings with black and white markings.',
        'habitat': 'Open Areas & Gardens',
        'common': 'Worldwide',
    },
    'PAPER KITE': {
        'scientific': 'Idea leuconoe',
        'desc': 'A large, elegant butterfly with translucent white wings veined in black, giving it a paper-like appearance as it floats gracefully.',
        'habitat': 'Tropical Forest Clearings',
        'common': 'Southeast Asia',
    },
    'PEACOCK': {
        'scientific': 'Aglais io',
        'desc': 'Named for the four bold eyespots on its red-brown wings, resembling peacock feathers. The dark underside mimics a dead leaf.',
        'habitat': 'Gardens & Woodland',
        'common': 'Europe & Temperate Asia',
    },
    'PINE WHITE': {
        'scientific': 'Neophasia menapia',
        'desc': 'A delicate white butterfly with thin black vein lines, strongly associated with coniferous forests. Females have orange-marked hindwings.',
        'habitat': 'Coniferous Forest',
        'common': 'Western North America',
    },
    'PIPEVINE SWALLOW': {
        'scientific': 'Battus philenor',
        'desc': 'A dark swallowtail with brilliant iridescent blue-green hindwings. Its toxicity from pipevine host plants makes it a model for mimicry.',
        'habitat': 'Forest & Woodland',
        'common': 'North America',
    },
    'POPINJAY': {
        'scientific': 'Stibochiona nicea',
        'desc': 'A brush-foot with dark brown wings accented by pale blue-green spots and wavy white lines. Its common name means a vain person.',
        'habitat': 'Tropical Montane Forest',
        'common': 'South & Southeast Asia',
    },
    'PURPLE HAIRSTREAK': {
        'scientific': 'Favonius quercus',
        'desc': 'Males shimmer with purple iridescence when sunlight hits their wings at the right angle. Often seen fluttering around oak canopies.',
        'habitat': 'Oak Woodland',
        'common': 'Europe',
    },
    'PURPLISH COPPER': {
        'scientific': 'Lycaena helloides',
        'desc': 'A small butterfly with coppery-orange upper wings shot through with purplish iridescence. The underside is paler with small black spots.',
        'habitat': 'Wet Meadows & Ditches',
        'common': 'Western North America',
    },
    'QUESTION MARK': {
        'scientific': 'Polygonia interrogationis',
        'desc': 'Named for the silver question-mark shape on its hindwing underside. The ragged wing margins provide leaf-like camouflage at rest.',
        'habitat': 'Deciduous Woodland',
        'common': 'Eastern North America',
    },
    'RED ADMIRAL': {
        'scientific': 'Vanessa atalanta',
        'desc': 'A striking butterfly with velvety black wings crossed by bold red-orange bands and white apical spots. A strong, territorial flier.',
        'habitat': 'Gardens & Woodland',
        'common': 'North America, Europe & Asia',
    },
    'RED CRACKER': {
        'scientific': 'Hamadryas amphinome',
        'desc': 'Named for the cracking sound males produce in flight. Its wings display a mosaic of red, blue, and grey patterns.',
        'habitat': 'Tropical Forest',
        'common': 'Central & South America',
    },
    'RED POSTMAN': {
        'scientific': 'Heliconius erato',
        'desc': 'A classic example of Müllerian mimicry. Its black wings with red forewing bands signal toxicity to predators.',
        'habitat': 'Tropical Forest Edge',
        'common': 'Central & South America',
    },
    'RED SPOTTED PURPLE': {
        'scientific': 'Limenitis arthemis',
        'desc': 'A mimic of the toxic Pipevine Swallowtail, featuring iridescent blue-black wings with red-orange spots on the underside.',
        'habitat': 'Deciduous Forest',
        'common': 'Eastern North America',
    },
    'SCARCE SWALLOW': {
        'scientific': 'Iphiclides podalirius',
        'desc': 'A pale swallowtail with bold black tiger stripes and long elegant tails. It soars and glides on hillside thermals.',
        'habitat': 'Warm Hillsides & Orchards',
        'common': 'Europe & Western Asia',
    },
    'SILVER SPOT SKIPPER': {
        'scientific': 'Hesperia comma',
        'desc': 'A small, robust skipper with warm orange-brown wings. The hindwing underside features distinctive silver-white spots on a greenish base.',
        'habitat': 'Chalk & Limestone Grassland',
        'common': 'Europe & North America',
    },
    'SLEEPY ORANGE': {
        'scientific': 'Eurema nicippe',
        'desc': 'A bright orange sulphur with a small dark "sleepy eye" mark on the upper forewing. Common and fast-flying across open areas.',
        'habitat': 'Open Fields & Roadsides',
        'common': 'North & Central America',
    },
    'SOOTYWING': {
        'scientific': 'Pholisora catullus',
        'desc': 'A tiny, dark skipper with sooty-brown wings sprinkled with small white dots. Often overlooked due to its small size and rapid flight.',
        'habitat': 'Disturbed Ground & Gardens',
        'common': 'North America',
    },
    'SOUTHERN DOGFACE': {
        'scientific': 'Zerene cesonia',
        'desc': 'A yellow sulphur butterfly whose forewing black markings form the silhouette of a poodle\'s face in profile — a delightful natural pattern.',
        'habitat': 'Open Fields & Desert',
        'common': 'Southern US to South America',
    },
    'STRAITED QUEEN': {
        'scientific': 'Danaus genutia',
        'desc': 'A tawny orange butterfly with black veins and white-spotted margins, closely resembling the Monarch. It is toxic to predators.',
        'habitat': 'Open Fields & Scrubland',
        'common': 'South & Southeast Asia',
    },
    'TROPICAL LEAFWING': {
        'scientific': 'Anaea aidea',
        'desc': 'The underside is a perfect dead-leaf mimic with vein-like lines and mottled brown tones. The upper wings flash brilliant orange-red.',
        'habitat': 'Tropical & Subtropical Forest',
        'common': 'Southern US to Central America',
    },
    'TWO BARRED FLASHER': {
        'scientific': 'Astraptes fulgerator',
        'desc': 'A large, showy skipper with dark wings that flash iridescent blue-green. Named for the two pale bars on the forewing.',
        'habitat': 'Tropical Forest Edges',
        'common': 'Southern US to South America',
    },
    'ULYSES': {
        'scientific': 'Papilio ulysses',
        'desc': 'A spectacular swallowtail with electric blue wings bordered in black. Commonly used as a tourism symbol in tropical Australia.',
        'habitat': 'Tropical Rainforest',
        'common': 'Australia & Southeast Asia',
    },
    'VICEROY': {
        'scientific': 'Limenitis archippus',
        'desc': 'Famous for mimicking the Monarch butterfly. Distinguished by an extra black line across the hindwing. Also toxic in its own right.',
        'habitat': 'Wetlands & Meadows',
        'common': 'North America',
    },
    'WOOD SATYR': {
        'scientific': 'Megisto cymela',
        'desc': 'A small, brown woodland butterfly with prominent eyespots on both wing surfaces. It has a characteristic bouncy, low flight.',
        'habitat': 'Shaded Woodland',
        'common': 'Eastern North America',
    },
    'YELLOW SWALLOW TAIL': {
        'scientific': 'Papilio glaucus',
        'desc': 'The Eastern Tiger Swallowtail is a large, bright yellow butterfly with bold black tiger stripes. Females may also occur in a dark morph.',
        'habitat': 'Deciduous Forest & Gardens',
        'common': 'Eastern North America',
    },
    'ZEBRA LONG WING': {
        'scientific': 'Heliconius charithonia',
        'desc': 'Florida\'s state butterfly, recognized by its long black wings with narrow yellow zebra-like stripes. Unusually long-lived for a butterfly.',
        'habitat': 'Tropical Hammocks & Gardens',
        'common': 'Southern US to Central America',
    },
}
